#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- create users
    CREATE USER $DB_STREAMLIT_USER WITH PASSWORD '$DB_STREAMLIT_PASSWORD';
    CREATE USER $DB_AIRFLOW_USER WITH PASSWORD '$DB_AIRFLOW_PASSWORD';

    -- add privileges to streamlit user
    GRANT CONNECT ON DATABASE $DB_NAME TO $DB_STREAMLIT_USER;
    GRANT USAGE ON SCHEMA public TO $DB_STREAMLIT_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_STREAMLIT_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $DB_STREAMLIT_USER;

    -- add privileges to airflow user
    GRANT CONNECT ON DATABASE $DB_NAME TO $DB_AIRFLOW_USER;
    GRANT USAGE ON SCHEMA public TO $DB_AIRFLOW_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DB_AIRFLOW_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $DB_AIRFLOW_USER;
EOSQL